/**
 * Marlin 3D Printer Firmware
 * Copyright (C) 2016 MarlinFirmware [https://github.com/MarlinFirmware/Marlin]
 *
 * Based on Sprinter and grbl.
 * Copyright (C) 2011 Camiel Gubbels / Erik van der Zalm
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 *
 */

/**
 * Chinese
 *
 * LCD Menu Messages
 * See also http://marlinfw.org/docs/development/lcd_language.html
 *
 */
#ifndef LANGUAGE_CN_H
#define LANGUAGE_CN_H

#define DISPLAY_CHARSET_ISO10646_CN

#define CN_WELCOME_MSG                         "\xa4\xa5\xa6\xa7"
#define CN_MSG_BACK                            "Back"
#define CN_MSG_SD_INSERTED                     "\xa8\xa9\xaa\xab"
#define CN_MSG_SD_REMOVED                      "\xa8\xa9\xac\xad"
#define MSG_LCD_ENDSTOPS                       "Endstops"
#define CN_MSG_MAIN                            "\xae\xaf\xb0"
#define CN_MSG_AUTOSTART                       "\xb1\xb2\xb3\xb4"
#define CN_MSG_DISABLE_STEPPERS                "\xb5\xb6\xb7\xb8\xb9\xba"
#define CN_MSG_DEBUG_MENU                      "Debug Menu"
#define CN_MSG_PROGRESS_BAR_TEST               "Progress Bar Test"
#define CN_MSG_AUTO_HOME                       "\xbb\xbc\xbd"
#define CN_MSG_AUTO_HOME_X                     "\xbb\xbc\xbd X"
#define CN_MSG_AUTO_HOME_Y                     "\xbb\xbc\xbd Y"
#define CN_MSG_AUTO_HOME_Z                     "\xbb\xbc\xbd Z"
#define CN_MSG_LEVEL_BED_HOMING                "Homing XYZ"
#define CN_MSG_LEVEL_BED_WAITING               "Click to Begin"
#define CN_MSG_LEVEL_BED_NEXT_POINT            "Next Point"
#define CN_MSG_LEVEL_BED_DONE                  "Leveling Done!"
#define CN_MSG_Z_FADE_HEIGHT                   "Fade Height"
#define CN_MSG_SET_HOME_OFFSETS                "\xbe\xbf\xbb\xbc\xbd\xc0\xc1"
#define CN_MSG_HOME_OFFSETS_APPLIED            "Offsets applied"
#define CN_MSG_SET_ORIGIN                      "\xbe\xbf\xbc\xbd"
#define CN_MSG_PREHEAT_1                       "\xc3\xc4 PLA"
#define CN_MSG_PREHEAT_1_N                     MSG_PREHEAT_1 " "
#define CN_MSG_PREHEAT_1_ALL                   MSG_PREHEAT_1 " \xc5\xc6"
#define CN_MSG_PREHEAT_1_END				   MSG_PREHEAT_1 " End"
#define CN_MSG_PREHEAT_1_BEDONLY               MSG_PREHEAT_1 " \xc4\xc7"
#define CN_MSG_PREHEAT_1_SETTINGS              MSG_PREHEAT_1 " \xbe\xbf"
#define CN_MSG_PREHEAT_2                       "\xc3\xc4 ABS"
#define CN_MSG_PREHEAT_2_N                     MSG_PREHEAT_2 " "
#define CN_MSG_PREHEAT_2_ALL                   MSG_PREHEAT_2 " \xc5\xc6"
#define CN_MSG_PREHEAT_2_END				   MSG_PREHEAT_2 " End"
#define CN_MSG_PREHEAT_2_BEDONLY               MSG_PREHEAT_2 " \xc4\xc7"
#define CN_MSG_PREHEAT_2_SETTINGS              MSG_PREHEAT_2 " \xbe\xbf"
#define CN_MSG_COOLDOWN                        "\xc8\xc9"
#define CN_MSG_SWITCH_PS_ON                    "\xb9\xcb\xca\xb3"
#define CN_MSG_SWITCH_PS_OFF                   "\xb9\xcb\xb5\xb6"
#define CN_MSG_EXTRUDE                         "\xcc\xad"
#define CN_MSG_RETRACT                         "\xbb\xcd"
#define CN_MSG_MOVE_AXIS                       "\xc1\xb2\xce"
#define CN_MSG_BED_LEVELING                    "\xb1\xb2\xcf\xd0"
#define CN_MSG_LEVEL_BED                       "\xcf\xe0\xc4\xc7"
#define CN_MSG_LEVEL_CORNERS                   "Level corners"
#define CN_MSG_NEXT_CORNER                     "Next corner"
#define MSG_EDITING_STOPPED                    "Mesh Editing Stopped"
#define CN_MSG_USER_MENU                       "Custom Commands"
#define MSG_UBL_DOING_G29                      "Doing G29"
#define MSG_UBL_UNHOMED                        "Home XYZ first"
#define CN_MSG_UBL_TOOLS                       "UBL Tools"
#define CN_MSG_UBL_LEVEL_BED                   "Unified Bed Leveling"
#define CN_MSG_UBL_MANUAL_MESH                 "Manually Build Mesh"
#define MSG_UBL_BC_INSERT                      "Place shim & measure"
#define MSG_UBL_BC_INSERT2                     "Measure"
#define MSG_UBL_BC_REMOVE                      "Remove & measure bed"
#define MSG_UBL_MOVING_TO_NEXT                 "Moving to next"
#define CN_MSG_UBL_ACTIVATE_MESH               "Activate UBL"
#define CN_MSG_UBL_DEACTIVATE_MESH             "Deactivate UBL"
#define CN_MSG_UBL_SET_BED_TEMP                "Bed Temp"
#define CN_MSG_UBL_CUSTOM_BED_TEMP             CN_MSG_UBL_SET_BED_TEMP
#define CN_MSG_UBL_SET_HOTEND_TEMP             "Hotend Temp"
#define CN_MSG_UBL_CUSTOM_HOTEND_TEMP          CN_MSG_UBL_SET_HOTEND_TEMP
#define CN_MSG_UBL_MESH_EDIT                   "Mesh Edit"
#define MSG_UBL_EDIT_CUSTOM_MESH               "Edit Custom Mesh"
#define MSG_UBL_FINE_TUNE_MESH                 "Fine Tuning Mesh"
#define MSG_UBL_DONE_EDITING_MESH              "Done Editing Mesh"
#define CN_MSG_UBL_BUILD_CUSTOM_MESH           "Build Custom Mesh"
#define CN_MSG_UBL_BUILD_MESH_MENU             "Build Mesh"
#define CN_MSG_UBL_BUILD_PLA_MESH              "Build PLA Mesh"
#define CN_MSG_UBL_BUILD_ABS_MESH              "Build ABS Mesh"
#define CN_MSG_UBL_BUILD_COLD_MESH             "Build Cold Mesh"
#define CN_MSG_UBL_MESH_HEIGHT_ADJUST          "Adjust Mesh Height"
#define CN_MSG_UBL_MESH_HEIGHT_AMOUNT          "Height Amount"
#define CN_MSG_UBL_VALIDATE_MESH_MENU          "Validate Mesh"
#define CN_MSG_UBL_VALIDATE_PLA_MESH           "Validate PLA Mesh"
#define CN_MSG_UBL_VALIDATE_ABS_MESH           "Validate ABS Mesh"
#define CN_MSG_UBL_VALIDATE_CUSTOM_MESH        "Validate Custom Mesh"
#define CN_MSG_UBL_CONTINUE_MESH               "Continue Bed Mesh"
#define CN_MSG_UBL_MESH_LEVELING               "Mesh Leveling"
#define CN_MSG_UBL_3POINT_MESH_LEVELING        "3-Point Leveling"
#define CN_MSG_UBL_GRID_MESH_LEVELING          "Grid Mesh Leveling"
#define CN_MSG_UBL_MESH_LEVEL                  "Level Mesh"
#define CN_MSG_UBL_SIDE_POINTS                 "Side Points"
#define MSG_UBL_MAP_TYPE                       "Map Type"
#define CN_MSG_UBL_OUTPUT_MAP                  "Output Mesh Map"
#define CN_MSG_UBL_OUTPUT_MAP_HOST             "Output for Host"
#define CN_MSG_UBL_OUTPUT_MAP_CSV              "Output for CSV"
#define CN_MSG_UBL_OUTPUT_MAP_BACKUP           "Off Printer Backup"
#define CN_MSG_UBL_INFO_UBL                    "Output UBL Info"
#define CN_MSG_UBL_EDIT_MESH_MENU              "Edit Mesh"
#define CN_MSG_UBL_FILLIN_AMOUNT               "Fill-in Amount"
#define CN_MSG_UBL_MANUAL_FILLIN               "Manual Fill-in"
#define CN_MSG_UBL_SMART_FILLIN                "Smart Fill-in"
#define CN_MSG_UBL_FILLIN_MESH                 "Fill-in Mesh"
#define CN_MSG_UBL_INVALIDATE_ALL              "Invalidate All"
#define CN_MSG_UBL_INVALIDATE_CLOSEST          "Invalidate Closest"
#define CN_MSG_UBL_FINE_TUNE_ALL               "Fine Tune All"
#define CN_MSG_UBL_FINE_TUNE_CLOSEST           "Fine Tune Closest"
#define CN_MSG_UBL_STORAGE_MESH_MENU           "Mesh Storage"
#define CN_MSG_UBL_STORAGE_SLOT                "Memory Slot"
#define CN_MSG_UBL_LOAD_MESH                   "Load Bed Mesh"
#define CN_MSG_UBL_SAVE_MESH                   "Save Bed Mesh"
#define CN_MSG_MESH_LOADED                     "Mesh %i loaded"
#define CN_MSG_MESH_SAVED                      "Mesh %i saved"
#define CN_MSG_NO_STORAGE                      "No storage"
#define MSG_UBL_SAVE_ERROR                     "Err: UBL Save"
#define MSG_UBL_RESTORE_ERROR                  "Err: UBL Restore"
#define MSG_UBL_Z_OFFSET_STOPPED               "Z-Offset Stopped"
#define CN_MSG_UBL_STEP_BY_STEP_MENU           "Step-By-Step UBL"
#define MSG_MOVING                             "Moving..."
#define CN_MSG_FREE_XY                         "Free XY"
#define CN_MSG_MOVE_X                          "\xc1\xb2 X"
#define CN_MSG_MOVE_Y                          "\xc1\xb2 Y"
#define CN_MSG_MOVE_Z                          "\xc1\xb2 Z"
#define CN_MSG_MOVE_E                          "\xcc\xad\xba"
#define CN_MSG_MOVE_01MM                       "\xc1\xb2 0.1mm"
#define CN_MSG_MOVE_1MM                        "\xc1\xb2 1mm"
#define CN_MSG_MOVE_10MM                       "\xc1\xb2 10mm"
#define CN_MSG_SPEED                           "\xd1\xd2"
#define CN_MSG_BED_Z                           "\xc4\xc7 Z"
#define CN_MSG_NOZZLE                          "\xd3\xd4"
#define CN_MSG_BED                             "\xc4\xc7"
#define CN_MSG_FAN_SPEED                       "\xd5\xd6\xd1\xd2"
#define CN_MSG_FLOW                            "\xcc\xad\xd1\xd2"
#define CN_MSG_CONTROL                         "\xd8\xd9"
#define CN_MSG_MIN                             LCD_STR_THERMOMETER " \xda\xdb"
#define CN_MSG_MAX                             LCD_STR_THERMOMETER " \xda\xdc"
#define CN_MSG_FACTOR                          LCD_STR_THERMOMETER " \xdd\xde"
#define CN_MSG_AUTOTEMP                        "\xb1\xb2\xd8\xc9"
#define CN_MSG_ON                              "On "  // intentional space to shift wide symbol to the left
#define CN_MSG_OFF                             "Off"  // intentional space to shift wide symbol to the left
#define CN_MSG_PID_P                           "PID-P"
#define CN_MSG_PID_I                           "PID-I"
#define CN_MSG_PID_D                           "PID-D"
#define CN_MSG_PID_C                           "PID-C"
#define CN_MSG_SELECT                          "Select"
#define CN_MSG_ACC                             "Accel"
#define CN_MSG_JERK                            "Jerk"
#define CN_MSG_VX_JERK                         "Vx-jerk"
#define CN_MSG_VY_JERK                         "Vy-jerk"
#define CN_MSG_VZ_JERK                         "Vz-jerk"
#define CN_MSG_VE_JERK                         "Ve-jerk"
#define CN_MSG_VELOCITY                        "Velocity"
#define CN_MSG_VMAX                            "Vmax "
#define CN_MSG_VMIN                            "Vmin"
#define CN_MSG_VTRAV_MIN                       "VTrav min"
#define CN_MSG_ACCELERATION                    "Acceleration"
#define CN_MSG_AMAX                            "Amax "
#define CN_MSG_A_RETRACT                       "A-retract"
#define CN_MSG_A_TRAVEL                        "A-travel"
#define CN_MSG_STEPS_PER_MM                    "Steps/mm"
#define CN_MSG_XSTEPS                          "Xsteps/mm"
#define CN_MSG_YSTEPS                          "Ysteps/mm"
#define CN_MSG_ZSTEPS                          "Zsteps/mm"
#define CN_MSG_ESTEPS                          "Esteps/mm"
#define CN_MSG_E1STEPS                         "E1steps/mm"
#define CN_MSG_E2STEPS                         "E2steps/mm"
#define CN_MSG_E3STEPS                         "E3steps/mm"
#define CN_MSG_E4STEPS                         "E4steps/mm"
#define CN_MSG_E5STEPS                         "E5steps/mm"
#define CN_MSG_TEMPERATURE                     "\xc9\xd2"
#define CN_MSG_MOTION                          "\xdf\xb2"
#define CN_MSG_FILAMENT                        "\xe0\xe1"
#define CN_MSG_VOLUMETRIC_ENABLED              "E in mm3"
#define CN_MSG_FILAMENT_DIAM                   "Fil. Dia."
#define CN_MSG_ADVANCE_K                       "Advance K"
#define CN_MSG_CONTRAST                        "LCD contrast"
#define CN_MSG_STORE_EEPROM                    "Store memory"
#define CN_MSG_LOAD_EEPROM                     "Load memory"
#define CN_MSG_RESTORE_FAILSAFE                "Restore failsafe"
#define CN_MSG_INIT_EEPROM                     "Initialize EEPROM"
#define CN_MSG_REFRESH                         "Refresh"
#define CN_MSG_WATCH                           "\xec\xed\xee\xef"
#define CN_MSG_PREPARE                         "\xa4\xa5"
#define CN_MSG_TUNE                            "\xcf\xf0"
#define CN_MSG_PAUSE_PRINT                     "\xf1\xf2\xca\xf3"
#define CN_MSG_RESUME_PRINT                    "\xf4\xf5\xca\xf3"
#define CN_MSG_STOP_PRINT                      "\xf2\xf6\xca\xf3"
#define CN_MSG_CARD_MENU                       "\xaf\xb0"
#define CN_MSG_NO_CARD                         "\xf9\xa8"
#define CN_MSG_DWELL                           "Sleep..."
#define CN_MSG_USERWAIT                        "Wait for user..."
#define MSG_PRINT_PAUSED                       "Print paused"
#define CN_MSG_RESUMING                        "Resuming print"
#define CN_MSG_PRINT_ABORTED                   "Print aborted"
#define CN_MSG_NO_MOVE                         "No move."
#define CN_MSG_KILLED                          "KILLED. "
#define CN_MSG_STOPPED                         "STOPPED. "
#define CN_MSG_CONTROL_RETRACT                 "Retract mm"
#define CN_MSG_CONTROL_RETRACT_SWAP            "Swap Re.mm"
#define CN_MSG_CONTROL_RETRACTF                "Retract  V"
#define CN_MSG_CONTROL_RETRACT_ZLIFT           "Hop mm"
#define CN_MSG_CONTROL_RETRACT_RECOVER         "UnRet mm"
#define CN_MSG_CONTROL_RETRACT_RECOVER_SWAP    "S UnRet mm"
#define CN_MSG_CONTROL_RETRACT_RECOVERF        "UnRet  V"
#define CN_MSG_AUTORETRACT                     "AutoRetr."
#define CN_MSG_FILAMENTCHANGE                  "Change filament"
#define CN_MSG_INIT_SDCARD                     "Init. TF card"
#define CN_MSG_CNG_SDCARD                      "Change TF card"
#define CN_MSG_ZPROBE_OUT                      "Z probe out. bed"
#define CN_MSG_BLTOUCH                         "BLTouch"
#define CN_MSG_BLTOUCH_SELFTEST                "BLTouch Self-Test"
#define CN_MSG_BLTOUCH_RESET                   "Reset BLTouch"
#define CN_MSG_BLTOUCH_DEPLOY                  "Deploy BLTouch"
#define CN_MSG_BLTOUCH_STOW                    "Stow BLTouch"
#define CN_MSG_BLTOUCH_SW_MODE                 "SW Deploy BLTouch"
#define CN_MSG_BLTOUCH_5V_MODE                 "BLTouch 5V Mode"
#define CN_MSG_BLTOUCH_OD_MODE                 "BLTouch OD Mode"
#define CN_MSG_HOME                            "Home"  // Used as MSG_HOME " " MSG_X MSG_Y MSG_Z " " MSG_FIRST
#define CN_MSG_FIRST                           "first"
#define CN_MSG_ZPROBE_ZOFFSET                  "Z Offset"
#define CN_MSG_BABYSTEP_X                      "Babystep X"
#define CN_MSG_BABYSTEP_Y                      "Babystep Y"
#define CN_MSG_BABYSTEP_Z                      "Babystep Z"
#define CN_MSG_ENDSTOP_ABORT                   "Endstop abort"
#define CN_MSG_HEATING_FAILED_LCD              "Heating failed"
#define CN_MSG_ERR_REDUNDANT_TEMP              "Err: REDUNDANT TEMP"
#define CN_MSG_THERMAL_RUNAWAY                 "THERMAL RUNAWAY"
#define CN_MSG_ERR_MAXTEMP                     "Err: MAXTEMP"
#define CN_MSG_ERR_MINTEMP                     "Err: MINTEMP"
#define CN_MSG_ERR_MAXTEMP_BED                 "Err: MAXTEMP BED"
#define MSG_ERR_MINTEMP_BED                    "Err: MINTEMP BED"
#define MSG_ERR_Z_HOMING                       "G28 Z Forbidden"
#define MSG_HALTED                             "PRINTER HALTED"
#define MSG_PLEASE_RESET                       "Please reset"
#define MSG_SHORT_DAY                          "d" // One character only
#define MSG_SHORT_HOUR                         "h" // One character only
#define MSG_SHORT_MINUTE                       "m" // One character only
#define MSG_HEATING                            "Heating..."
#define MSG_HEATING_COMPLETE                   "Heating done."
#define MSG_BED_HEATING                        "Bed Heating."
#define MSG_BED_DONE                           "Bed done."
#define MSG_DELTA_CALIBRATE                    "Delta Calibration"
#define MSG_DELTA_CALIBRATE_X                  "Calibrate X"
#define MSG_DELTA_CALIBRATE_Y                  "Calibrate Y"
#define MSG_DELTA_CALIBRATE_Z                  "Calibrate Z"
#define MSG_DELTA_CALIBRATE_CENTER             "Calibrate Center"
#define CN_MSG_DELTA_SETTINGS                  "Delta Settings"
#define CN_MSG_DELTA_AUTO_CALIBRATE            "Auto Calibration"
#define CN_MSG_DELTA_HEIGHT_CALIBRATE          "Set Delta Height"
#define CN_MSG_DELTA_DIAG_ROG                  "Diag Rod"
#define CN_MSG_DELTA_HEIGHT                    "Height"
#define CN_MSG_DELTA_RADIUS                    "Radius"
#define CN_MSG_INFO_MENU                       "About Printer"
#define CN_MSG_INFO_PRINTER_MENU               "Printer Info"
#define CN_MSG_3POINT_LEVELING                 "3-Point Leveling"
#define CN_MSG_LINEAR_LEVELING                 "Linear Leveling"
#define CN_MSG_BILINEAR_LEVELING               "Bilinear Leveling"
#define CN_MSG_UBL_LEVELING                    "Unified Bed Leveling"
#define CN_MSG_MESH_LEVELING                   "Mesh Leveling"
#define CN_MSG_INFO_STATS_MENU                 "Printer Stats"
#define CN_MSG_INFO_BOARD_MENU                 "Board Info"
#define CN_MSG_INFO_THERMISTOR_MENU            "Thermistors"
#define CN_MSG_INFO_EXTRUDERS                  "Extruders"
#define CN_MSG_INFO_BAUDRATE                   "Baud"
#define CN_MSG_INFO_PROTOCOL                   "Protocol"
#define CN_MSG_CASE_LIGHT                      "Case light"
#define CN_MSG_CASE_LIGHT_BRIGHTNESS           "Light BRIGHTNESS"
#if LCD_WIDTH >= 20
  #define CN_MSG_INFO_PRINT_COUNT              "Print Count"
  #define CN_MSG_INFO_COMPLETED_PRINTS         "Completed"
  #define CN_MSG_INFO_PRINT_TIME               "Total print time"
  #define CN_MSG_INFO_PRINT_LONGEST            "Longest job time"
  #define CN_MSG_INFO_PRINT_FILAMENT           "Extruded total"
#else
  #define CN_MSG_INFO_PRINT_COUNT              "Prints"
  #define CN_MSG_INFO_COMPLETED_PRINTS         "Completed"
  #define CN_MSG_INFO_PRINT_TIME               "Total"
  #define CN_MSG_INFO_PRINT_LONGEST            "Longest"
  #define CN_MSG_INFO_PRINT_FILAMENT           "Extruded"
#endif
#define CN_MSG_INFO_MIN_TEMP                   "Min Temp"
#define CN_MSG_INFO_MAX_TEMP                   "Max Temp"
#define CN_MSG_INFO_PSU                        "PSU"
#define CN_MSG_DRIVE_STRENGTH                  "Drive Strength"
#define CN_MSG_DAC_PERCENT                     "Driver %"
#define CN_MSG_DAC_EEPROM_WRITE                "DAC EEPROM Write"
#define CN_MSG_FILAMENT_CHANGE_HEADER          "PRINT PAUSED"
#define CN_MSG_FILAMENT_CHANGE_OPTION_HEADER   "RESUME OPTIONS:"
#define CN_MSG_FILAMENT_CHANGE_OPTION_EXTRUDE  "Extrude more"
#define CN_MSG_FILAMENT_CHANGE_OPTION_RESUME   "Resume print"
#define CN_MSG_FILAMENT_CHANGE_MINTEMP         "Minimum Temp is "
#define CN_MSG_FILAMENT_CHANGE_NOZZLE          "  Nozzle: "
#define MSG_ERR_HOMING_FAILED                  "Homing failed"
#define MSG_ERR_PROBING_FAILED                 "Probing failed"
#define CN_MSG_SELECT_LANGUAGE                 "Language"
#define CN_MSG_ENGLISH_LANGUAGE                "English"
#define CN_MSG_CHINESE_LANGUAGE                "Chinese"
#define CN_MSG_POWER_LOSS_RECOVERY             "\xa4\xa5\xf4\xf5\xca\xf3 ?"
#define CN_MSG_WEBSITE_URL_MENU                "www.cxsw3d.com"
#endif // LANGUAGE_CN_H
